#ifndef __RISCV_VECTOR_V0P10_XTHEADVDOT_H
#define __RISCV_VECTOR_V0P10_XTHEADVDOT_H
#define vpnclip_wv_i8m1(...) __riscv_th_vpnclip_wv_i8m1(__VA_ARGS__)
#define vpnclip_wv_i8m2(...) __riscv_th_vpnclip_wv_i8m2(__VA_ARGS__)
#define vpnclip_wv_i8m4(...) __riscv_th_vpnclip_wv_i8m4(__VA_ARGS__)
#define vpnclip_wv_i8mf2(...) __riscv_th_vpnclip_wv_i8mf2(__VA_ARGS__)
#define vpnclip_wv_i8mf4(...) __riscv_th_vpnclip_wv_i8mf4(__VA_ARGS__)
#define vpnclip_wv_i8mf8(...) __riscv_th_vpnclip_wv_i8mf8(__VA_ARGS__)
#define vpnclip_wx_i8m1(...) __riscv_th_vpnclip_wx_i8m1(__VA_ARGS__)
#define vpnclip_wx_i8m2(...) __riscv_th_vpnclip_wx_i8m2(__VA_ARGS__)
#define vpnclip_wx_i8m4(...) __riscv_th_vpnclip_wx_i8m4(__VA_ARGS__)
#define vpnclip_wx_i8mf2(...) __riscv_th_vpnclip_wx_i8mf2(__VA_ARGS__)
#define vpnclip_wx_i8mf4(...) __riscv_th_vpnclip_wx_i8mf4(__VA_ARGS__)
#define vpnclip_wx_i8mf8(...) __riscv_th_vpnclip_wx_i8mf8(__VA_ARGS__)
#define vpnclipu_wv_u8m1(...) __riscv_th_vpnclipu_wv_u8m1(__VA_ARGS__)
#define vpnclipu_wv_u8m2(...) __riscv_th_vpnclipu_wv_u8m2(__VA_ARGS__)
#define vpnclipu_wv_u8m4(...) __riscv_th_vpnclipu_wv_u8m4(__VA_ARGS__)
#define vpnclipu_wv_u8mf2(...) __riscv_th_vpnclipu_wv_u8mf2(__VA_ARGS__)
#define vpnclipu_wv_u8mf4(...) __riscv_th_vpnclipu_wv_u8mf4(__VA_ARGS__)
#define vpnclipu_wv_u8mf8(...) __riscv_th_vpnclipu_wv_u8mf8(__VA_ARGS__)
#define vpnclipu_wx_u8m1(...) __riscv_th_vpnclipu_wx_u8m1(__VA_ARGS__)
#define vpnclipu_wx_u8m2(...) __riscv_th_vpnclipu_wx_u8m2(__VA_ARGS__)
#define vpnclipu_wx_u8m4(...) __riscv_th_vpnclipu_wx_u8m4(__VA_ARGS__)
#define vpnclipu_wx_u8mf2(...) __riscv_th_vpnclipu_wx_u8mf2(__VA_ARGS__)
#define vpnclipu_wx_u8mf4(...) __riscv_th_vpnclipu_wx_u8mf4(__VA_ARGS__)
#define vpnclipu_wx_u8mf8(...) __riscv_th_vpnclipu_wx_u8mf8(__VA_ARGS__)
#define vpwadd_vv_i16m1(...) __riscv_th_vpwadd_vv_i16m1(__VA_ARGS__)
#define vpwadd_vv_i16m2(...) __riscv_th_vpwadd_vv_i16m2(__VA_ARGS__)
#define vpwadd_vv_i16m4(...) __riscv_th_vpwadd_vv_i16m4(__VA_ARGS__)
#define vpwadd_vv_i16m8(...) __riscv_th_vpwadd_vv_i16m8(__VA_ARGS__)
#define vpwadd_vv_i16mf2(...) __riscv_th_vpwadd_vv_i16mf2(__VA_ARGS__)
#define vpwadd_vv_i16mf4(...) __riscv_th_vpwadd_vv_i16mf4(__VA_ARGS__)
#define vpwadd_vx_i16m1(...) __riscv_th_vpwadd_vx_i16m1(__VA_ARGS__)
#define vpwadd_vx_i16m2(...) __riscv_th_vpwadd_vx_i16m2(__VA_ARGS__)
#define vpwadd_vx_i16m4(...) __riscv_th_vpwadd_vx_i16m4(__VA_ARGS__)
#define vpwadd_vx_i16m8(...) __riscv_th_vpwadd_vx_i16m8(__VA_ARGS__)
#define vpwadd_vx_i16mf2(...) __riscv_th_vpwadd_vx_i16mf2(__VA_ARGS__)
#define vpwadd_vx_i16mf4(...) __riscv_th_vpwadd_vx_i16mf4(__VA_ARGS__)
#define vpwaddu_vv_u16m1(...) __riscv_th_vpwaddu_vv_u16m1(__VA_ARGS__)
#define vpwaddu_vv_u16m2(...) __riscv_th_vpwaddu_vv_u16m2(__VA_ARGS__)
#define vpwaddu_vv_u16m4(...) __riscv_th_vpwaddu_vv_u16m4(__VA_ARGS__)
#define vpwaddu_vv_u16m8(...) __riscv_th_vpwaddu_vv_u16m8(__VA_ARGS__)
#define vpwaddu_vv_u16mf2(...) __riscv_th_vpwaddu_vv_u16mf2(__VA_ARGS__)
#define vpwaddu_vv_u16mf4(...) __riscv_th_vpwaddu_vv_u16mf4(__VA_ARGS__)
#define vpwaddu_vx_u16m1(...) __riscv_th_vpwaddu_vx_u16m1(__VA_ARGS__)
#define vpwaddu_vx_u16m2(...) __riscv_th_vpwaddu_vx_u16m2(__VA_ARGS__)
#define vpwaddu_vx_u16m4(...) __riscv_th_vpwaddu_vx_u16m4(__VA_ARGS__)
#define vpwaddu_vx_u16m8(...) __riscv_th_vpwaddu_vx_u16m8(__VA_ARGS__)
#define vpwaddu_vx_u16mf2(...) __riscv_th_vpwaddu_vx_u16mf2(__VA_ARGS__)
#define vpwaddu_vx_u16mf4(...) __riscv_th_vpwaddu_vx_u16mf4(__VA_ARGS__)
#define vmaqa_vv_i32m1(...) __riscv_th_vmaqa_vv_i32m1(__VA_ARGS__)
#define vmaqa_vv_i32m2(...) __riscv_th_vmaqa_vv_i32m2(__VA_ARGS__)
#define vmaqa_vv_i32m4(...) __riscv_th_vmaqa_vv_i32m4(__VA_ARGS__)
#define vmaqa_vv_i32m8(...) __riscv_th_vmaqa_vv_i32m8(__VA_ARGS__)
#define vmaqa_vv_i32mf2(...) __riscv_th_vmaqa_vv_i32mf2(__VA_ARGS__)
#define vmaqa_vx_i32m1(...) __riscv_th_vmaqa_vx_i32m1(__VA_ARGS__)
#define vmaqa_vx_i32m2(...) __riscv_th_vmaqa_vx_i32m2(__VA_ARGS__)
#define vmaqa_vx_i32m4(...) __riscv_th_vmaqa_vx_i32m4(__VA_ARGS__)
#define vmaqa_vx_i32m8(...) __riscv_th_vmaqa_vx_i32m8(__VA_ARGS__)
#define vmaqa_vx_i32mf2(...) __riscv_th_vmaqa_vx_i32mf2(__VA_ARGS__)
#define vmaqasu_vv_i32m1(...) __riscv_th_vmaqasu_vv_i32m1(__VA_ARGS__)
#define vmaqasu_vv_i32m2(...) __riscv_th_vmaqasu_vv_i32m2(__VA_ARGS__)
#define vmaqasu_vv_i32m4(...) __riscv_th_vmaqasu_vv_i32m4(__VA_ARGS__)
#define vmaqasu_vv_i32m8(...) __riscv_th_vmaqasu_vv_i32m8(__VA_ARGS__)
#define vmaqasu_vv_i32mf2(...) __riscv_th_vmaqasu_vv_i32mf2(__VA_ARGS__)
#define vmaqasu_vx_i32m1(...) __riscv_th_vmaqasu_vx_i32m1(__VA_ARGS__)
#define vmaqasu_vx_i32m2(...) __riscv_th_vmaqasu_vx_i32m2(__VA_ARGS__)
#define vmaqasu_vx_i32m4(...) __riscv_th_vmaqasu_vx_i32m4(__VA_ARGS__)
#define vmaqasu_vx_i32m8(...) __riscv_th_vmaqasu_vx_i32m8(__VA_ARGS__)
#define vmaqasu_vx_i32mf2(...) __riscv_th_vmaqasu_vx_i32mf2(__VA_ARGS__)
#define vmaqau_vv_u32m1(...) __riscv_th_vmaqau_vv_u32m1(__VA_ARGS__)
#define vmaqau_vv_u32m2(...) __riscv_th_vmaqau_vv_u32m2(__VA_ARGS__)
#define vmaqau_vv_u32m4(...) __riscv_th_vmaqau_vv_u32m4(__VA_ARGS__)
#define vmaqau_vv_u32m8(...) __riscv_th_vmaqau_vv_u32m8(__VA_ARGS__)
#define vmaqau_vv_u32mf2(...) __riscv_th_vmaqau_vv_u32mf2(__VA_ARGS__)
#define vmaqau_vx_u32m1(...) __riscv_th_vmaqau_vx_u32m1(__VA_ARGS__)
#define vmaqau_vx_u32m2(...) __riscv_th_vmaqau_vx_u32m2(__VA_ARGS__)
#define vmaqau_vx_u32m4(...) __riscv_th_vmaqau_vx_u32m4(__VA_ARGS__)
#define vmaqau_vx_u32m8(...) __riscv_th_vmaqau_vx_u32m8(__VA_ARGS__)
#define vmaqau_vx_u32mf2(...) __riscv_th_vmaqau_vx_u32mf2(__VA_ARGS__)
#define vmaqaus_vx_i32m1(...) __riscv_th_vmaqaus_vx_i32m1(__VA_ARGS__)
#define vmaqaus_vx_i32m2(...) __riscv_th_vmaqaus_vx_i32m2(__VA_ARGS__)
#define vmaqaus_vx_i32m4(...) __riscv_th_vmaqaus_vx_i32m4(__VA_ARGS__)
#define vmaqaus_vx_i32m8(...) __riscv_th_vmaqaus_vx_i32m8(__VA_ARGS__)
#define vmaqaus_vx_i32mf2(...) __riscv_th_vmaqaus_vx_i32mf2(__VA_ARGS__)
#define vpmaqa_vv_i32m1(...) __riscv_th_vpmaqa_vv_i32m1(__VA_ARGS__)
#define vpmaqa_vv_i32m2(...) __riscv_th_vpmaqa_vv_i32m2(__VA_ARGS__)
#define vpmaqa_vv_i32m4(...) __riscv_th_vpmaqa_vv_i32m4(__VA_ARGS__)
#define vpmaqa_vv_i32m8(...) __riscv_th_vpmaqa_vv_i32m8(__VA_ARGS__)
#define vpmaqa_vv_i32mf2(...) __riscv_th_vpmaqa_vv_i32mf2(__VA_ARGS__)
#define vpmaqa_vx_i32m1(...) __riscv_th_vpmaqa_vx_i32m1(__VA_ARGS__)
#define vpmaqa_vx_i32m2(...) __riscv_th_vpmaqa_vx_i32m2(__VA_ARGS__)
#define vpmaqa_vx_i32m4(...) __riscv_th_vpmaqa_vx_i32m4(__VA_ARGS__)
#define vpmaqa_vx_i32m8(...) __riscv_th_vpmaqa_vx_i32m8(__VA_ARGS__)
#define vpmaqa_vx_i32mf2(...) __riscv_th_vpmaqa_vx_i32mf2(__VA_ARGS__)
#define vpmaqasu_vv_i32m1(...) __riscv_th_vpmaqasu_vv_i32m1(__VA_ARGS__)
#define vpmaqasu_vv_i32m2(...) __riscv_th_vpmaqasu_vv_i32m2(__VA_ARGS__)
#define vpmaqasu_vv_i32m4(...) __riscv_th_vpmaqasu_vv_i32m4(__VA_ARGS__)
#define vpmaqasu_vv_i32m8(...) __riscv_th_vpmaqasu_vv_i32m8(__VA_ARGS__)
#define vpmaqasu_vv_i32mf2(...) __riscv_th_vpmaqasu_vv_i32mf2(__VA_ARGS__)
#define vpmaqasu_vx_i32m1(...) __riscv_th_vpmaqasu_vx_i32m1(__VA_ARGS__)
#define vpmaqasu_vx_i32m2(...) __riscv_th_vpmaqasu_vx_i32m2(__VA_ARGS__)
#define vpmaqasu_vx_i32m4(...) __riscv_th_vpmaqasu_vx_i32m4(__VA_ARGS__)
#define vpmaqasu_vx_i32m8(...) __riscv_th_vpmaqasu_vx_i32m8(__VA_ARGS__)
#define vpmaqasu_vx_i32mf2(...) __riscv_th_vpmaqasu_vx_i32mf2(__VA_ARGS__)
#define vpmaqau_vv_u32m1(...) __riscv_th_vpmaqau_vv_u32m1(__VA_ARGS__)
#define vpmaqau_vv_u32m2(...) __riscv_th_vpmaqau_vv_u32m2(__VA_ARGS__)
#define vpmaqau_vv_u32m4(...) __riscv_th_vpmaqau_vv_u32m4(__VA_ARGS__)
#define vpmaqau_vv_u32m8(...) __riscv_th_vpmaqau_vv_u32m8(__VA_ARGS__)
#define vpmaqau_vv_u32mf2(...) __riscv_th_vpmaqau_vv_u32mf2(__VA_ARGS__)
#define vpmaqau_vx_u32m1(...) __riscv_th_vpmaqau_vx_u32m1(__VA_ARGS__)
#define vpmaqau_vx_u32m2(...) __riscv_th_vpmaqau_vx_u32m2(__VA_ARGS__)
#define vpmaqau_vx_u32m4(...) __riscv_th_vpmaqau_vx_u32m4(__VA_ARGS__)
#define vpmaqau_vx_u32m8(...) __riscv_th_vpmaqau_vx_u32m8(__VA_ARGS__)
#define vpmaqau_vx_u32mf2(...) __riscv_th_vpmaqau_vx_u32mf2(__VA_ARGS__)
#define vpmaqaus_vx_i32m1(...) __riscv_th_vpmaqaus_vx_i32m1(__VA_ARGS__)
#define vpmaqaus_vx_i32m2(...) __riscv_th_vpmaqaus_vx_i32m2(__VA_ARGS__)
#define vpmaqaus_vx_i32m4(...) __riscv_th_vpmaqaus_vx_i32m4(__VA_ARGS__)
#define vpmaqaus_vx_i32m8(...) __riscv_th_vpmaqaus_vx_i32m8(__VA_ARGS__)
#define vpmaqaus_vx_i32mf2(...) __riscv_th_vpmaqaus_vx_i32mf2(__VA_ARGS__)
#define vmaqa_vv_i32m1_m(...) __riscv_th_vmaqa_vv_i32m1_m(__VA_ARGS__)
#define vmaqa_vv_i32m2_m(...) __riscv_th_vmaqa_vv_i32m2_m(__VA_ARGS__)
#define vmaqa_vv_i32m4_m(...) __riscv_th_vmaqa_vv_i32m4_m(__VA_ARGS__)
#define vmaqa_vv_i32m8_m(...) __riscv_th_vmaqa_vv_i32m8_m(__VA_ARGS__)
#define vmaqa_vv_i32mf2_m(...) __riscv_th_vmaqa_vv_i32mf2_m(__VA_ARGS__)
#define vmaqa_vx_i32m1_m(...) __riscv_th_vmaqa_vx_i32m1_m(__VA_ARGS__)
#define vmaqa_vx_i32m2_m(...) __riscv_th_vmaqa_vx_i32m2_m(__VA_ARGS__)
#define vmaqa_vx_i32m4_m(...) __riscv_th_vmaqa_vx_i32m4_m(__VA_ARGS__)
#define vmaqa_vx_i32m8_m(...) __riscv_th_vmaqa_vx_i32m8_m(__VA_ARGS__)
#define vmaqa_vx_i32mf2_m(...) __riscv_th_vmaqa_vx_i32mf2_m(__VA_ARGS__)
#define vmaqasu_vv_i32m1_m(...) __riscv_th_vmaqasu_vv_i32m1_m(__VA_ARGS__)
#define vmaqasu_vv_i32m2_m(...) __riscv_th_vmaqasu_vv_i32m2_m(__VA_ARGS__)
#define vmaqasu_vv_i32m4_m(...) __riscv_th_vmaqasu_vv_i32m4_m(__VA_ARGS__)
#define vmaqasu_vv_i32m8_m(...) __riscv_th_vmaqasu_vv_i32m8_m(__VA_ARGS__)
#define vmaqasu_vv_i32mf2_m(...) __riscv_th_vmaqasu_vv_i32mf2_m(__VA_ARGS__)
#define vmaqasu_vx_i32m1_m(...) __riscv_th_vmaqasu_vx_i32m1_m(__VA_ARGS__)
#define vmaqasu_vx_i32m2_m(...) __riscv_th_vmaqasu_vx_i32m2_m(__VA_ARGS__)
#define vmaqasu_vx_i32m4_m(...) __riscv_th_vmaqasu_vx_i32m4_m(__VA_ARGS__)
#define vmaqasu_vx_i32m8_m(...) __riscv_th_vmaqasu_vx_i32m8_m(__VA_ARGS__)
#define vmaqasu_vx_i32mf2_m(...) __riscv_th_vmaqasu_vx_i32mf2_m(__VA_ARGS__)
#define vmaqau_vv_u32m1_m(...) __riscv_th_vmaqau_vv_u32m1_m(__VA_ARGS__)
#define vmaqau_vv_u32m2_m(...) __riscv_th_vmaqau_vv_u32m2_m(__VA_ARGS__)
#define vmaqau_vv_u32m4_m(...) __riscv_th_vmaqau_vv_u32m4_m(__VA_ARGS__)
#define vmaqau_vv_u32m8_m(...) __riscv_th_vmaqau_vv_u32m8_m(__VA_ARGS__)
#define vmaqau_vv_u32mf2_m(...) __riscv_th_vmaqau_vv_u32mf2_m(__VA_ARGS__)
#define vmaqau_vx_u32m1_m(...) __riscv_th_vmaqau_vx_u32m1_m(__VA_ARGS__)
#define vmaqau_vx_u32m2_m(...) __riscv_th_vmaqau_vx_u32m2_m(__VA_ARGS__)
#define vmaqau_vx_u32m4_m(...) __riscv_th_vmaqau_vx_u32m4_m(__VA_ARGS__)
#define vmaqau_vx_u32m8_m(...) __riscv_th_vmaqau_vx_u32m8_m(__VA_ARGS__)
#define vmaqau_vx_u32mf2_m(...) __riscv_th_vmaqau_vx_u32mf2_m(__VA_ARGS__)
#define vmaqaus_vx_i32m1_m(...) __riscv_th_vmaqaus_vx_i32m1_m(__VA_ARGS__)
#define vmaqaus_vx_i32m2_m(...) __riscv_th_vmaqaus_vx_i32m2_m(__VA_ARGS__)
#define vmaqaus_vx_i32m4_m(...) __riscv_th_vmaqaus_vx_i32m4_m(__VA_ARGS__)
#define vmaqaus_vx_i32m8_m(...) __riscv_th_vmaqaus_vx_i32m8_m(__VA_ARGS__)
#define vmaqaus_vx_i32mf2_m(...) __riscv_th_vmaqaus_vx_i32mf2_m(__VA_ARGS__)
#define vpmaqa_vv_i32m1_m(...) __riscv_th_vpmaqa_vv_i32m1_m(__VA_ARGS__)
#define vpmaqa_vv_i32m2_m(...) __riscv_th_vpmaqa_vv_i32m2_m(__VA_ARGS__)
#define vpmaqa_vv_i32m4_m(...) __riscv_th_vpmaqa_vv_i32m4_m(__VA_ARGS__)
#define vpmaqa_vv_i32m8_m(...) __riscv_th_vpmaqa_vv_i32m8_m(__VA_ARGS__)
#define vpmaqa_vv_i32mf2_m(...) __riscv_th_vpmaqa_vv_i32mf2_m(__VA_ARGS__)
#define vpmaqa_vx_i32m1_m(...) __riscv_th_vpmaqa_vx_i32m1_m(__VA_ARGS__)
#define vpmaqa_vx_i32m2_m(...) __riscv_th_vpmaqa_vx_i32m2_m(__VA_ARGS__)
#define vpmaqa_vx_i32m4_m(...) __riscv_th_vpmaqa_vx_i32m4_m(__VA_ARGS__)
#define vpmaqa_vx_i32m8_m(...) __riscv_th_vpmaqa_vx_i32m8_m(__VA_ARGS__)
#define vpmaqa_vx_i32mf2_m(...) __riscv_th_vpmaqa_vx_i32mf2_m(__VA_ARGS__)
#define vpmaqasu_vv_i32m1_m(...) __riscv_th_vpmaqasu_vv_i32m1_m(__VA_ARGS__)
#define vpmaqasu_vv_i32m2_m(...) __riscv_th_vpmaqasu_vv_i32m2_m(__VA_ARGS__)
#define vpmaqasu_vv_i32m4_m(...) __riscv_th_vpmaqasu_vv_i32m4_m(__VA_ARGS__)
#define vpmaqasu_vv_i32m8_m(...) __riscv_th_vpmaqasu_vv_i32m8_m(__VA_ARGS__)
#define vpmaqasu_vv_i32mf2_m(...) __riscv_th_vpmaqasu_vv_i32mf2_m(__VA_ARGS__)
#define vpmaqasu_vx_i32m1_m(...) __riscv_th_vpmaqasu_vx_i32m1_m(__VA_ARGS__)
#define vpmaqasu_vx_i32m2_m(...) __riscv_th_vpmaqasu_vx_i32m2_m(__VA_ARGS__)
#define vpmaqasu_vx_i32m4_m(...) __riscv_th_vpmaqasu_vx_i32m4_m(__VA_ARGS__)
#define vpmaqasu_vx_i32m8_m(...) __riscv_th_vpmaqasu_vx_i32m8_m(__VA_ARGS__)
#define vpmaqasu_vx_i32mf2_m(...) __riscv_th_vpmaqasu_vx_i32mf2_m(__VA_ARGS__)
#define vpmaqau_vv_u32m1_m(...) __riscv_th_vpmaqau_vv_u32m1_m(__VA_ARGS__)
#define vpmaqau_vv_u32m2_m(...) __riscv_th_vpmaqau_vv_u32m2_m(__VA_ARGS__)
#define vpmaqau_vv_u32m4_m(...) __riscv_th_vpmaqau_vv_u32m4_m(__VA_ARGS__)
#define vpmaqau_vv_u32m8_m(...) __riscv_th_vpmaqau_vv_u32m8_m(__VA_ARGS__)
#define vpmaqau_vv_u32mf2_m(...) __riscv_th_vpmaqau_vv_u32mf2_m(__VA_ARGS__)
#define vpmaqau_vx_u32m1_m(...) __riscv_th_vpmaqau_vx_u32m1_m(__VA_ARGS__)
#define vpmaqau_vx_u32m2_m(...) __riscv_th_vpmaqau_vx_u32m2_m(__VA_ARGS__)
#define vpmaqau_vx_u32m4_m(...) __riscv_th_vpmaqau_vx_u32m4_m(__VA_ARGS__)
#define vpmaqau_vx_u32m8_m(...) __riscv_th_vpmaqau_vx_u32m8_m(__VA_ARGS__)
#define vpmaqau_vx_u32mf2_m(...) __riscv_th_vpmaqau_vx_u32mf2_m(__VA_ARGS__)
#define vpmaqaus_vx_i32m1_m(...) __riscv_th_vpmaqaus_vx_i32m1_m(__VA_ARGS__)
#define vpmaqaus_vx_i32m2_m(...) __riscv_th_vpmaqaus_vx_i32m2_m(__VA_ARGS__)
#define vpmaqaus_vx_i32m4_m(...) __riscv_th_vpmaqaus_vx_i32m4_m(__VA_ARGS__)
#define vpmaqaus_vx_i32m8_m(...) __riscv_th_vpmaqaus_vx_i32m8_m(__VA_ARGS__)
#define vpmaqaus_vx_i32mf2_m(...) __riscv_th_vpmaqaus_vx_i32mf2_m(__VA_ARGS__)
#define vpnclip_wv_i8m1_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wv_i8m1_m(mask, op1, op2, vl)
#define vpnclip_wv_i8m2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wv_i8m2_m(mask, op1, op2, vl)
#define vpnclip_wv_i8m4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wv_i8m4_m(mask, op1, op2, vl)
#define vpnclip_wv_i8mf2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wv_i8mf2_m(mask, op1, op2, vl)
#define vpnclip_wv_i8mf4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wv_i8mf4_m(mask, op1, op2, vl)
#define vpnclip_wv_i8mf8_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wv_i8mf8_m(mask, op1, op2, vl)
#define vpnclip_wx_i8m1_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wx_i8m1_m(mask, op1, op2, vl)
#define vpnclip_wx_i8m2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wx_i8m2_m(mask, op1, op2, vl)
#define vpnclip_wx_i8m4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wx_i8m4_m(mask, op1, op2, vl)
#define vpnclip_wx_i8mf2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wx_i8mf2_m(mask, op1, op2, vl)
#define vpnclip_wx_i8mf4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wx_i8mf4_m(mask, op1, op2, vl)
#define vpnclip_wx_i8mf8_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclip_wx_i8mf8_m(mask, op1, op2, vl)
#define vpnclipu_wv_u8m1_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wv_u8m1_m(mask, op1, op2, vl)
#define vpnclipu_wv_u8m2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wv_u8m2_m(mask, op1, op2, vl)
#define vpnclipu_wv_u8m4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wv_u8m4_m(mask, op1, op2, vl)
#define vpnclipu_wv_u8mf2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wv_u8mf2_m(mask, op1, op2, vl)
#define vpnclipu_wv_u8mf4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wv_u8mf4_m(mask, op1, op2, vl)
#define vpnclipu_wv_u8mf8_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wv_u8mf8_m(mask, op1, op2, vl)
#define vpnclipu_wx_u8m1_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wx_u8m1_m(mask, op1, op2, vl)
#define vpnclipu_wx_u8m2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wx_u8m2_m(mask, op1, op2, vl)
#define vpnclipu_wx_u8m4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wx_u8m4_m(mask, op1, op2, vl)
#define vpnclipu_wx_u8mf2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wx_u8mf2_m(mask, op1, op2, vl)
#define vpnclipu_wx_u8mf4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wx_u8mf4_m(mask, op1, op2, vl)
#define vpnclipu_wx_u8mf8_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpnclipu_wx_u8mf8_m(mask, op1, op2, vl)
#define vpwadd_vv_i16m1_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vv_i16m1_m(mask, op1, op2, vl)
#define vpwadd_vv_i16m2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vv_i16m2_m(mask, op1, op2, vl)
#define vpwadd_vv_i16m4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vv_i16m4_m(mask, op1, op2, vl)
#define vpwadd_vv_i16m8_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vv_i16m8_m(mask, op1, op2, vl)
#define vpwadd_vv_i16mf2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vv_i16mf2_m(mask, op1, op2, vl)
#define vpwadd_vv_i16mf4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vv_i16mf4_m(mask, op1, op2, vl)
#define vpwadd_vx_i16m1_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vx_i16m1_m(mask, op1, op2, vl)
#define vpwadd_vx_i16m2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vx_i16m2_m(mask, op1, op2, vl)
#define vpwadd_vx_i16m4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vx_i16m4_m(mask, op1, op2, vl)
#define vpwadd_vx_i16m8_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vx_i16m8_m(mask, op1, op2, vl)
#define vpwadd_vx_i16mf2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vx_i16mf2_m(mask, op1, op2, vl)
#define vpwadd_vx_i16mf4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwadd_vx_i16mf4_m(mask, op1, op2, vl)
#define vpwaddu_vv_u16m1_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vv_u16m1_m(mask, op1, op2, vl)
#define vpwaddu_vv_u16m2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vv_u16m2_m(mask, op1, op2, vl)
#define vpwaddu_vv_u16m4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vv_u16m4_m(mask, op1, op2, vl)
#define vpwaddu_vv_u16m8_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vv_u16m8_m(mask, op1, op2, vl)
#define vpwaddu_vv_u16mf2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vv_u16mf2_m(mask, op1, op2, vl)
#define vpwaddu_vv_u16mf4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vv_u16mf4_m(mask, op1, op2, vl)
#define vpwaddu_vx_u16m1_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vx_u16m1_m(mask, op1, op2, vl)
#define vpwaddu_vx_u16m2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vx_u16m2_m(mask, op1, op2, vl)
#define vpwaddu_vx_u16m4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vx_u16m4_m(mask, op1, op2, vl)
#define vpwaddu_vx_u16m8_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vx_u16m8_m(mask, op1, op2, vl)
#define vpwaddu_vx_u16mf2_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vx_u16mf2_m(mask, op1, op2, vl)
#define vpwaddu_vx_u16mf4_m(mask, maskedoff, op1, op2, vl) __riscv_th_vpwaddu_vx_u16mf4_m(mask, op1, op2, vl)
#endif